wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.7.6
    start_time: 1647746479
    t:
      1:
      - 1
      4: 3.7.6
      5: 0.12.11
      8:
      - 2
      - 3
      - 5
amp:
  desc: null
  value: false
batch_size:
  desc: null
  value: 4
epochs:
  desc: null
  value: 1
img_scale:
  desc: null
  value: 0.5
learning_rate:
  desc: null
  value: 1.0e-05
save_checkpoint:
  desc: null
  value: true
val_percent:
  desc: null
  value: 0.1
